# Generated by Django 2.2 on 2023-06-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=500)),
                ('Last_name', models.CharField(max_length=500)),
                ('Employee_id', models.CharField(max_length=500)),
                ('Employee_designation', models.CharField(max_length=500)),
                ('Employee_qualification', models.CharField(max_length=500)),
                ('Employee_experience', models.CharField(max_length=500)),
                ('Employee_phoneno', models.CharField(max_length=500)),
                ('Employee_email', models.EmailField(max_length=500)),
                ('Employee_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.Department')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=500)),
                ('Last_name', models.CharField(max_length=500)),
                ('Student_id', models.CharField(max_length=500)),
                ('Student_course', models.CharField(max_length=500)),
                ('Student_sem', models.CharField(max_length=500)),
                ('Join_year', models.DateField()),
                ('Pass_year', models.DateField()),
                ('Student_phoneno', models.CharField(max_length=500)),
                ('Student_email', models.EmailField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('TechTechnology', models.CharField(max_length=500)),
                ('Github', models.CharField(max_length=500)),
                ('Documentation', models.FileField(upload_to='projects/pdf')),
                ('PPt', models.FileField(upload_to='projects/ppt')),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.Domain')),
                ('Guide', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(default=1)),
                ('quantity', models.IntegerField()),
                ('distributed', models.IntegerField()),
                ('date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.InventoryCategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.InventoryStatus')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.Streams')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='faculty.InventorySubCategory')),
            ],
        ),
    ]
